spring:
  application:
    name: oss-example
  cloud:
    alicloud:
      access-key: a
      secret-key: a
      oss:
        endpoint: oss-cn-qingdao.aliyuncs.com
server:
  port: 18084
management:
  endpoints:
    web:
      exposure:
        include: '*'